$axure.loadCurrentPage({
  "url":"flow_gesamt.html",
  "generationDate":new Date(1396968461434.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"535f430c1e1b4e1bb8f1a2e0f8a975c3",
    "type":"Axure:Page",
    "name":"Flow gesamt",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b626279530c14c2bbe4100bc09ff3683",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3A9CEA},
            "location":{
              "x":310,
              "y":100},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f56243b0f934fc99cf32ddb13b8d4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3A9CEA},
                "location":{
                  "x":310,
                  "y":100},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u0.png"},
          "referencePageUrl":"login.html"},
{
          "id":"a9b9f33b00ac4ae2992e4f3700fd7e32",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF49D68F},
            "location":{
              "x":150,
              "y":530},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757d020af82a41e89d97298fc6a1ef28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF49D68F},
                "location":{
                  "x":150,
                  "y":530},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u2.png"}},
{
          "id":"8163e45fdca14dd18fa532745b97b020",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF49D68F},
            "location":{
              "x":150,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1706abfde50b444da1f9332a0a79b89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF49D68F},
                "location":{
                  "x":150,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u2.png"},
          "referencePageUrl":"registrierung.html"},
{
          "id":"35d082f0c9a2435094abd37a07aecb1d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6CF6},
            "location":{
              "x":295,
              "y":210},
            "size":{
              "width":130,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a1b5cc9392b4d7e9a8f37245d9c01f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6CF6},
                "location":{
                  "x":295,
                  "y":210},
                "size":{
                  "width":130,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u6.png"}},
{
          "id":"3c6040c1e5234f93a43a96306e589dc3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF49D68F},
            "location":{
              "x":150,
              "y":640},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c602601de124177ab44590dbcffca54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF49D68F},
                "location":{
                  "x":150,
                  "y":640},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u2.png"},
          "referencePageUrl":"fb_selbstkonzept.html"},
{
          "id":"50de0b531ee3485b8d409b6cfc5e73c5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFEBA546},
            "location":{
              "x":390,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f39dd6771cff49bb8c7acaafd0337acf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEBA546},
                "location":{
                  "x":390,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u10.png"},
          "referencePageUrl":"beispiel.html"},
{
          "id":"3ee9a7c0e0b64aceaef421f23aa54a60",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3A9CEA},
            "location":{
              "x":640,
              "y":410},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa6d0141225d4f66b4979886779a1a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3A9CEA},
                "location":{
                  "x":640,
                  "y":410},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u0.png"},
          "referencePageUrl":"auswahlseite.html"},
{
          "id":"99ed99782950418db09a3640e236562d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3A9CEA},
            "location":{
              "x":540,
              "y":530},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1783ea1661f046958057da2a087878a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3A9CEA},
                "location":{
                  "x":540,
                  "y":530},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u0.png"},
          "referencePageUrl":"erfolg.html"},
{
          "id":"1f7722701cd447b7b1f4f7fe96f8bb24",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF3A9CEA},
            "location":{
              "x":750,
              "y":530},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ad20085e0f41cbaa6f10b7d62f4c30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3A9CEA},
                "location":{
                  "x":750,
                  "y":530},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/flow_gesamt/u0.png"},
          "referencePageUrl":"problem.html"},
{
          "id":"6227f6ef5fee43dd8fa9c1b58c2a5ede",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcf791b5d1ea410b86d3596018f2b5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":160}},
              "adaptiveStyles":{
}}]},
{
          "id":"5564387a58d744f59bd7726426fd7468",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":288}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c45eb9e70b444d28e0e294baeb5dd03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":288}},
              "adaptiveStyles":{
}}]},
{
          "id":"7b6b26a1fcaf4cd38f4d8ba9ce6d4d7d",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"234b80e4fa64442799f50fe1d55310fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":410}},
              "adaptiveStyles":{
}}]},
{
          "id":"7840abbef26843949ca97cf6ae240583",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d50963b79f494cbe88c57ee130c5efcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":470}},
              "adaptiveStyles":{
}}]},
{
          "id":"0fe125af1660406ebfed9bdf26e5ba2b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec3783576004a71a7738a04ea4de8da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":530}},
              "adaptiveStyles":{
}}]},
{
          "id":"76ccf1bff77a49d09044f3073afdcf47",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fb3d039fc18470e83b8d8c76b30e86a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":470}},
              "adaptiveStyles":{
}}]},
{
          "id":"03ca9d1f26a043fe904835352e3fff32",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bb0aaf0e07b401ead78e018f00a2a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":590}},
              "adaptiveStyles":{
}}]},
{
          "id":"64247243f0f045849d8aa352d3c26adc",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":440}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d9185bddaa44411854f0b43ce84a147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":440}},
              "adaptiveStyles":{
}}]},
{
          "id":"038fdd866ef24280989248b54930ea8c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":670}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f16a24b28c87497e897bd293e57ee734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":670}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "b626279530c14c2bbe4100bc09ff3683":{
      "scriptId":"u0"},
    "1f56243b0f934fc99cf32ddb13b8d4c7":{
      "scriptId":"u1"},
    "a9b9f33b00ac4ae2992e4f3700fd7e32":{
      "scriptId":"u2"},
    "757d020af82a41e89d97298fc6a1ef28":{
      "scriptId":"u3"},
    "8163e45fdca14dd18fa532745b97b020":{
      "scriptId":"u4"},
    "1706abfde50b444da1f9332a0a79b89a":{
      "scriptId":"u5"},
    "35d082f0c9a2435094abd37a07aecb1d":{
      "scriptId":"u6"},
    "4a1b5cc9392b4d7e9a8f37245d9c01f0":{
      "scriptId":"u7"},
    "3c6040c1e5234f93a43a96306e589dc3":{
      "scriptId":"u8"},
    "2c602601de124177ab44590dbcffca54":{
      "scriptId":"u9"},
    "50de0b531ee3485b8d409b6cfc5e73c5":{
      "scriptId":"u10"},
    "f39dd6771cff49bb8c7acaafd0337acf":{
      "scriptId":"u11"},
    "3ee9a7c0e0b64aceaef421f23aa54a60":{
      "scriptId":"u12"},
    "fa6d0141225d4f66b4979886779a1a1f":{
      "scriptId":"u13"},
    "99ed99782950418db09a3640e236562d":{
      "scriptId":"u14"},
    "1783ea1661f046958057da2a087878a2":{
      "scriptId":"u15"},
    "1f7722701cd447b7b1f4f7fe96f8bb24":{
      "scriptId":"u16"},
    "a5ad20085e0f41cbaa6f10b7d62f4c30":{
      "scriptId":"u17"},
    "6227f6ef5fee43dd8fa9c1b58c2a5ede":{
      "scriptId":"u18"},
    "fcf791b5d1ea410b86d3596018f2b5cc":{
      "scriptId":"u19"},
    "5564387a58d744f59bd7726426fd7468":{
      "scriptId":"u20"},
    "1c45eb9e70b444d28e0e294baeb5dd03":{
      "scriptId":"u21"},
    "7b6b26a1fcaf4cd38f4d8ba9ce6d4d7d":{
      "scriptId":"u22"},
    "234b80e4fa64442799f50fe1d55310fd":{
      "scriptId":"u23"},
    "7840abbef26843949ca97cf6ae240583":{
      "scriptId":"u24"},
    "d50963b79f494cbe88c57ee130c5efcf":{
      "scriptId":"u25"},
    "0fe125af1660406ebfed9bdf26e5ba2b":{
      "scriptId":"u26"},
    "2ec3783576004a71a7738a04ea4de8da":{
      "scriptId":"u27"},
    "76ccf1bff77a49d09044f3073afdcf47":{
      "scriptId":"u28"},
    "2fb3d039fc18470e83b8d8c76b30e86a":{
      "scriptId":"u29"},
    "03ca9d1f26a043fe904835352e3fff32":{
      "scriptId":"u30"},
    "3bb0aaf0e07b401ead78e018f00a2a99":{
      "scriptId":"u31"},
    "64247243f0f045849d8aa352d3c26adc":{
      "scriptId":"u32"},
    "2d9185bddaa44411854f0b43ce84a147":{
      "scriptId":"u33"},
    "038fdd866ef24280989248b54930ea8c":{
      "scriptId":"u34"},
    "f16a24b28c87497e897bd293e57ee734":{
      "scriptId":"u35"}}});