$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1396968458872.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3655a330402a4bf0ba287df420135351",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6ffc49c36bb84f7f86c8c9e4dae46b31",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"97cfbbb019e448e68a5fc0a227525933",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":75},
            "size":{
              "width":300,
              "height":190},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4eb3dc3c7a948a9ba165f1b6491671f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":75},
                "size":{
                  "width":300,
                  "height":190},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u7.png"}},
{
          "id":"7a6f85729b1a442cb85b5942d2f9c6c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":155},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d54462f8cb4749ab318dc9b7fcc62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":155},
                "size":{
                  "width":300,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"3c2776d0f2054b7c910d394a4dbb2296",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":110},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"8d4a6913140c4d4a819dafc5ad9de14b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":185},
            "size":{
              "width":280,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"a4e9d525c57741ce82a00c21de3a11f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":50,
              "y":280},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C4},
            "linePattern":"solid",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"730eecd393fd477eb67a4243d4562d3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":50,
                  "y":280},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C4},
                "linePattern":"solid",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Auswahlseite in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"auswahlseite.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/startseite/u4.png"}},
{
          "id":"a54f83038b874bb094eab743b65f3739",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF43445B,
              "opacity":1},
            "location":{
              "x":20,
              "y":235},
            "size":{
              "width":150,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f16c8ee41444beaa2be7a586b8fb33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF43445B,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":235},
                "size":{
                  "width":150,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"0024ca0c9b72407996dac0ededf46e59",
          "label":"PasswortZurueck",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":90,
              "y":340},
            "size":{
              "width":126,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f5b536a96749fa8445a7eef16b647f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":340},
                "size":{
                  "width":126,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Passwort in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"passwort.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}}},
  "objectPaths":{
    "6ffc49c36bb84f7f86c8c9e4dae46b31":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "97cfbbb019e448e68a5fc0a227525933":{
      "scriptId":"u7"},
    "d4eb3dc3c7a948a9ba165f1b6491671f":{
      "scriptId":"u8"},
    "7a6f85729b1a442cb85b5942d2f9c6c6":{
      "scriptId":"u9"},
    "e2d54462f8cb4749ab318dc9b7fcc62d":{
      "scriptId":"u10"},
    "3c2776d0f2054b7c910d394a4dbb2296":{
      "scriptId":"u11"},
    "8d4a6913140c4d4a819dafc5ad9de14b":{
      "scriptId":"u12"},
    "a4e9d525c57741ce82a00c21de3a11f0":{
      "scriptId":"u13"},
    "730eecd393fd477eb67a4243d4562d3d":{
      "scriptId":"u14"},
    "a54f83038b874bb094eab743b65f3739":{
      "scriptId":"u15"},
    "47f16c8ee41444beaa2be7a586b8fb33":{
      "scriptId":"u16"},
    "0024ca0c9b72407996dac0ededf46e59":{
      "scriptId":"u17"},
    "f1f5b536a96749fa8445a7eef16b647f":{
      "scriptId":"u18"}}});