$axure.loadCurrentPage({
  "url":"pc_nutzung.html",
  "generationDate":new Date(1396968453651.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"78b25bc6499d45918104fedaee9b984d",
    "type":"Axure:Page",
    "name":"PC Nutzung",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5529274d3edf45d8ac5923635291d524",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"9756d897834a4c8f91e07b2788896237",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7a37b6891a6142f5b5a9acb79824ff58"},
{
          "id":"0185672c7baa40a1b317a4603d683f15",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":105},
            "size":{
              "width":310,
              "height":443}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"998f3a5d47fc47f98d142fac85f8f7d5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1c11c2e4169a4722892b6eaf3a6722a9",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEBE7B3},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":500},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39e9a2b7565542fa9e06f0ea2b9545ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEBE7B3},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":10,
                          "height":500},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pc_nutzung/u17.png"}},
{
                  "id":"c1f71d57582d4941b72f1467ee22eb33",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":95}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6e77d3bf37e43b28c6991a34c1eca22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":95}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pc_nutzung/u19.png"}},
{
                  "id":"4abc2996852f467896268c887d021b60",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":50},
                    "size":{
                      "width":280,
                      "height":35}},
                  "adaptiveStyles":{
}},
{
                  "id":"c41b751a3d804432898c2c689e9864af",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":105},
                    "size":{
                      "width":300,
                      "height":95}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2dedcbf9de345f7875b9ffedd10b7d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":105},
                        "size":{
                          "width":300,
                          "height":95}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pc_nutzung/u19.png"}},
{
                  "id":"68a031ecad3b42a5adeba5ceca6d951e",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":155},
                    "size":{
                      "width":280,
                      "height":35}},
                  "adaptiveStyles":{
}},
{
                  "id":"2b7d6baac85c4f33a7020aff5804a41f",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":300,
                      "height":110}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81bb83ca2794460b92cfb6633bedaece",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":210},
                        "size":{
                          "width":300,
                          "height":110}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/bildung___beruf/u16.png"}},
{
                  "id":"6b59689d636242168bac5db3184f11dd",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":330},
                    "size":{
                      "width":300,
                      "height":110}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1012db1d7a2642779f739cc06a8f2cd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":330},
                        "size":{
                          "width":300,
                          "height":110}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/bildung___beruf/u16.png"}},
{
                  "id":"7c960421d39647468b4161962394d65f",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":275},
                    "size":{
                      "width":280,
                      "height":35}},
                  "adaptiveStyles":{
}},
{
                  "id":"80294b3fbe664d03a07739e2d587fa4e",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":395},
                    "size":{
                      "width":280,
                      "height":35}},
                  "adaptiveStyles":{
}},
{
                  "id":"a16a4edc917f4c5f938a622d165e41bf",
                  "label":"",
                  "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":450},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9873ca0e6ba042e9a9538737c65db16f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0185672c7baa40a1b317a4603d683f15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":450},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open PC Kenntnisse in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"pc_kenntnisse.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"547cb4fe8bfb46dfadc5addd61f32884",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c114e9fe3f451d8849a32bb1c7de0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"3e701c96f7ff42d5a965671ab93d84ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":45,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a270fa0f6ff4e6c9df0fc229c840fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":45,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"c2f82befbec84c149255c8f27bfbefee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFEFFFE,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60be7b9abb8641d099bcec5cb93a39e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFEFFFE,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":70,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u24.png"}},
{
          "id":"f258a127331145d0bb2fcd4d6c22b851",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":95,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f555040cc7418d9f4349e67c712dbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":95,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"6df404eb90ca455eae8c5946c50c5749",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":120,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dc9947d9bdd49aa9d2aa94c897d61de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":120,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}},
    "7a37b6891a6142f5b5a9acb79824ff58":{
      "packageId":"7a37b6891a6142f5b5a9acb79824ff58",
      "type":"Axure:Master",
      "name":"Master Registrierung",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"75adf6f749014a10be2ea38894d0ff55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":55,
                "y":0},
              "size":{
                "width":265,
                "height":60},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68cbf0eece824d31b1220db2183b25a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":55,
                    "y":0},
                  "size":{
                    "width":265,
                    "height":60},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u8.png"}},
{
            "id":"470b815c9bb1491e93076b3163d6d959",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial'",
              "opacity":"1",
              "location":{
                "x":65,
                "y":21},
              "size":{
                "width":126,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c52e4711cc3491faad8084185273f60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial'",
                  "opacity":"1",
                  "location":{
                    "x":65,
                    "y":21},
                  "size":{
                    "width":126,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f4cc8beddcf34ae08a39d3198ed73974",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF5F8F9},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5e30c0764e4c41708e4425a0bd5b110a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF5F8F9},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alter_geschlecht/u12.png"}},
{
            "id":"0699841899a2417685f75b75c11cf0fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEBE7B3},
              "location":{
                "x":0,
                "y":95},
              "size":{
                "width":320,
                "height":453},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aa3b59a5f3d4dfe995ab4b83b709569",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEBE7B3},
                  "location":{
                    "x":0,
                    "y":95},
                  "size":{
                    "width":320,
                    "height":453},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alter_geschlecht/u14.png"}}]}}},
  "objectPaths":{
    "5529274d3edf45d8ac5923635291d524":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "9756d897834a4c8f91e07b2788896237":{
      "scriptId":"u7",
      "75adf6f749014a10be2ea38894d0ff55":{
        "scriptId":"u8"},
      "68cbf0eece824d31b1220db2183b25a5":{
        "scriptId":"u9"},
      "470b815c9bb1491e93076b3163d6d959":{
        "scriptId":"u10"},
      "8c52e4711cc3491faad8084185273f60":{
        "scriptId":"u11"},
      "f4cc8beddcf34ae08a39d3198ed73974":{
        "scriptId":"u12"},
      "5e30c0764e4c41708e4425a0bd5b110a":{
        "scriptId":"u13"},
      "0699841899a2417685f75b75c11cf0fe":{
        "scriptId":"u14"},
      "1aa3b59a5f3d4dfe995ab4b83b709569":{
        "scriptId":"u15"}},
    "0185672c7baa40a1b317a4603d683f15":{
      "scriptId":"u16"},
    "1c11c2e4169a4722892b6eaf3a6722a9":{
      "scriptId":"u17"},
    "39e9a2b7565542fa9e06f0ea2b9545ea":{
      "scriptId":"u18"},
    "c1f71d57582d4941b72f1467ee22eb33":{
      "scriptId":"u19"},
    "b6e77d3bf37e43b28c6991a34c1eca22":{
      "scriptId":"u20"},
    "4abc2996852f467896268c887d021b60":{
      "scriptId":"u21"},
    "c41b751a3d804432898c2c689e9864af":{
      "scriptId":"u22"},
    "d2dedcbf9de345f7875b9ffedd10b7d8":{
      "scriptId":"u23"},
    "68a031ecad3b42a5adeba5ceca6d951e":{
      "scriptId":"u24"},
    "2b7d6baac85c4f33a7020aff5804a41f":{
      "scriptId":"u25"},
    "81bb83ca2794460b92cfb6633bedaece":{
      "scriptId":"u26"},
    "6b59689d636242168bac5db3184f11dd":{
      "scriptId":"u27"},
    "1012db1d7a2642779f739cc06a8f2cd3":{
      "scriptId":"u28"},
    "7c960421d39647468b4161962394d65f":{
      "scriptId":"u29"},
    "80294b3fbe664d03a07739e2d587fa4e":{
      "scriptId":"u30"},
    "a16a4edc917f4c5f938a622d165e41bf":{
      "scriptId":"u31"},
    "9873ca0e6ba042e9a9538737c65db16f":{
      "scriptId":"u32"},
    "547cb4fe8bfb46dfadc5addd61f32884":{
      "scriptId":"u33"},
    "11c114e9fe3f451d8849a32bb1c7de0d":{
      "scriptId":"u34"},
    "3e701c96f7ff42d5a965671ab93d84ff":{
      "scriptId":"u35"},
    "8a270fa0f6ff4e6c9df0fc229c840fc3":{
      "scriptId":"u36"},
    "c2f82befbec84c149255c8f27bfbefee":{
      "scriptId":"u37"},
    "60be7b9abb8641d099bcec5cb93a39e0":{
      "scriptId":"u38"},
    "f258a127331145d0bb2fcd4d6c22b851":{
      "scriptId":"u39"},
    "78f555040cc7418d9f4349e67c712dbf":{
      "scriptId":"u40"},
    "6df404eb90ca455eae8c5946c50c5749":{
      "scriptId":"u41"},
    "2dc9947d9bdd49aa9d2aa94c897d61de":{
      "scriptId":"u42"}}});