$axure.loadCurrentPage({
  "url":"registrierung.html",
  "generationDate":new Date(1396968453038.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"72c6a56a043a4f93ab7850b3737aec37",
    "type":"Axure:Page",
    "name":"Registrierung",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e882c16de5984bc38e4eb59e38a7f862",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"4f50faddb57a490bb0377049757aa5e2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"94e1ba9c9ea64f238340c06d076dd56e"},
{
          "id":"056210b321034e698230dae60fe33e22",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":75},
            "size":{
              "width":310,
              "height":473}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ae2c1ba17fb249d2be72e163be22bb89",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7c7f8bacb843452e9e86771eccdb7045",
                  "label":"",
                  "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":820},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db72f13039ce49f4b0f93f43b434db3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":820},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u15.png"}},
{
                  "id":"c2fbc50f990c4811969cb8059c17b150",
                  "label":"",
                  "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEBE7B3},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":830},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a9e4b986b13486381917425176c8677",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEBE7B3},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":10,
                          "height":830},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u17.png"}},
{
                  "id":"8e365a2794dd4731a1728c0d84d7ffff",
                  "label":"",
                  "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":10,
                      "y":300},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a07796aae7c471084ea52a71f3d5653",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":10,
                          "y":300},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u19.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"5486a6c84cb74fa6b958e619c7c6b653",
                  "label":"",
                  "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":10,
                      "y":345},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b88ee57d214418496f0259995803a7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":10,
                          "y":345},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u19.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"94af4f57cb984b088b62743f4035d09c",
                  "label":"",
                  "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":50,
                      "y":768},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"429313700dd64ff1af4c8ea156c0450c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"056210b321034e698230dae60fe33e22",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":50,
                          "y":768},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Alter Geschlecht in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"alter_geschlecht.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0d2c4c7d71b84e38ada4451c231009e2",
          "label":"Menu",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":120,
              "y":65},
            "size":{
              "width":200,
              "height":210},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17165c570e324fb083e5e0d2e3d27076",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":200,
                  "height":210}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee5ca5d35c174d579416ba618c545e63",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "size":{
                      "width":200,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6eb16c5c79e4a42a2cd1d88f2b03689",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "size":{
                          "width":200,
                          "height":42},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u27.png"}},
{
                  "id":"14b3b0a1b3b14abdb468d6cf3ae870f3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":0,
                      "y":126},
                    "size":{
                      "width":200,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01209edc10c7425b8419f3582af9ebdc",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":0,
                          "y":126},
                        "size":{
                          "width":200,
                          "height":42},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u27.png"}},
{
                  "id":"2c6715b38dfb4f4b9e49cd2bc255d5f4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":0,
                      "y":168},
                    "size":{
                      "width":200,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0beaf2aefa7842bda06a1c488ef4b888",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":0,
                          "y":168},
                        "size":{
                          "width":200,
                          "height":42},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u35.png"}},
{
                  "id":"00083fc2567f4552a3d79bab2d71425b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":200,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b116684b72ea428a8550b909092abb4c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":0,
                          "y":42},
                        "size":{
                          "width":200,
                          "height":42},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u27.png"}},
{
                  "id":"89a6551a81b74c89812e378ee1ca1080",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":0,
                      "y":84},
                    "size":{
                      "width":200,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"baa9c892a94946618921446e988f1b25",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":0,
                          "y":84},
                        "size":{
                          "width":200,
                          "height":42},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/registrierung/u27.png"}}]}]},
{
          "id":"35a2823c0eef41c58c8639bed75f8cd0",
          "label":"MenuButton",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":260,
              "y":0},
            "size":{
              "width":60,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82b94a8e474340208fe97c48413517e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":260,
                  "y":0},
                "size":{
                  "width":60,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide Menu,<br>icon_Erfolg,<br>icon_Beispiel,<br>icon_Problem,<br>icon_Kontakt,<br>icon_Profil",
                      "objectsToFades":[{
                          "objectPath":["0d2c4c7d71b84e38ada4451c231009e2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ba2c91fd75f24da68bc4e871125db871"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d3d67662549249b3a320be333195ecaa"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["57b0c843ed8144e9836e242a4b68a7e9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5e3b3046b12d494db255a051c6bf12df"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["703e949747cc4c72bff439faed35c6f6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show Menu,<br>icon_Erfolg,<br>icon_Beispiel,<br>icon_Problem,<br>icon_Kontakt,<br>icon_Profil",
                      "objectsToFades":[{
                          "objectPath":["0d2c4c7d71b84e38ada4451c231009e2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["ba2c91fd75f24da68bc4e871125db871"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d3d67662549249b3a320be333195ecaa"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["57b0c843ed8144e9836e242a4b68a7e9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5e3b3046b12d494db255a051c6bf12df"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["703e949747cc4c72bff439faed35c6f6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/registrierung/menubutton_u37.png"}},
{
          "id":"084cb8fc7eea47438296cd3e557a6a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":24},
            "size":{
              "width":25,
              "height":3},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3668c67a4df45578446979a3e57a390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":24},
                "size":{
                  "width":25,
                  "height":3},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/u39.png"}},
{
          "id":"fb4f07ea39b3473b8bafb41de496e1bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":31},
            "size":{
              "width":25,
              "height":3},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86be1c6fc8d0415b8b26c06e1aa2c4ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":31},
                "size":{
                  "width":25,
                  "height":3},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/u39.png"}},
{
          "id":"4b12669e8fb54878850ded7b0a677f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":38},
            "size":{
              "width":25,
              "height":3},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d47dba651cb4e8a827d7d9de9c2ed39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":38},
                "size":{
                  "width":25,
                  "height":3},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/u39.png"}},
{
          "id":"ba2c91fd75f24da68bc4e871125db871",
          "label":"icon_Erfolg",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":121,
              "y":108},
            "size":{
              "width":40,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea24e9ac1f524c88a19c3e202a1a9691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":121,
                  "y":108},
                "size":{
                  "width":40,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/icon_erfolg_u45.jpg"}},
{
          "id":"d3d67662549249b3a320be333195ecaa",
          "label":"icon_Beispiel",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":121,
              "y":66},
            "size":{
              "width":40,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596c21f4a7ce4e9db849599a513a59a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":121,
                  "y":66},
                "size":{
                  "width":40,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/icon_beispiel_u47.jpg"}},
{
          "id":"57b0c843ed8144e9836e242a4b68a7e9",
          "label":"icon_Problem",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":121,
              "y":150},
            "size":{
              "width":40,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e5dbdcc4024b13babf18d5a4fc8141",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":121,
                  "y":150},
                "size":{
                  "width":40,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/icon_problem_u49.jpg"}},
{
          "id":"5e3b3046b12d494db255a051c6bf12df",
          "label":"icon_Kontakt",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":121,
              "y":192},
            "size":{
              "width":40,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"122fb1240e224dd1be53f60526daf381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":121,
                  "y":192},
                "size":{
                  "width":40,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/icon_kontakt_u51.jpg"}},
{
          "id":"703e949747cc4c72bff439faed35c6f6",
          "label":"icon_Profil",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":121,
              "y":234},
            "size":{
              "width":40,
              "height":40},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e55183bd8694ebb958dee3f312d30b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":121,
                  "y":234},
                "size":{
                  "width":40,
                  "height":40},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/registrierung/icon_profil_u53.jpg"}}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}},
    "94e1ba9c9ea64f238340c06d076dd56e":{
      "packageId":"94e1ba9c9ea64f238340c06d076dd56e",
      "type":"Axure:Master",
      "name":"Master Registrierung start",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"75adf6f749014a10be2ea38894d0ff55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":55,
                "y":0},
              "size":{
                "width":265,
                "height":60},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68cbf0eece824d31b1220db2183b25a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":55,
                    "y":0},
                  "size":{
                    "width":265,
                    "height":60},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u8.png"}},
{
            "id":"470b815c9bb1491e93076b3163d6d959",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial'",
              "opacity":"1",
              "location":{
                "x":65,
                "y":21},
              "size":{
                "width":126,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c52e4711cc3491faad8084185273f60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial'",
                  "opacity":"1",
                  "location":{
                    "x":65,
                    "y":21},
                  "size":{
                    "width":126,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0699841899a2417685f75b75c11cf0fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEBE7B3},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aa3b59a5f3d4dfe995ab4b83b709569",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEBE7B3},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u12.png"}}]}}},
  "objectPaths":{
    "e882c16de5984bc38e4eb59e38a7f862":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "4f50faddb57a490bb0377049757aa5e2":{
      "scriptId":"u7",
      "75adf6f749014a10be2ea38894d0ff55":{
        "scriptId":"u8"},
      "68cbf0eece824d31b1220db2183b25a5":{
        "scriptId":"u9"},
      "470b815c9bb1491e93076b3163d6d959":{
        "scriptId":"u10"},
      "8c52e4711cc3491faad8084185273f60":{
        "scriptId":"u11"},
      "0699841899a2417685f75b75c11cf0fe":{
        "scriptId":"u12"},
      "1aa3b59a5f3d4dfe995ab4b83b709569":{
        "scriptId":"u13"}},
    "056210b321034e698230dae60fe33e22":{
      "scriptId":"u14"},
    "7c7f8bacb843452e9e86771eccdb7045":{
      "scriptId":"u15"},
    "db72f13039ce49f4b0f93f43b434db3a":{
      "scriptId":"u16"},
    "c2fbc50f990c4811969cb8059c17b150":{
      "scriptId":"u17"},
    "4a9e4b986b13486381917425176c8677":{
      "scriptId":"u18"},
    "8e365a2794dd4731a1728c0d84d7ffff":{
      "scriptId":"u19"},
    "3a07796aae7c471084ea52a71f3d5653":{
      "scriptId":"u20"},
    "5486a6c84cb74fa6b958e619c7c6b653":{
      "scriptId":"u21"},
    "9b88ee57d214418496f0259995803a7a":{
      "scriptId":"u22"},
    "94af4f57cb984b088b62743f4035d09c":{
      "scriptId":"u23"},
    "429313700dd64ff1af4c8ea156c0450c":{
      "scriptId":"u24"},
    "0d2c4c7d71b84e38ada4451c231009e2":{
      "scriptId":"u25"},
    "17165c570e324fb083e5e0d2e3d27076":{
      "scriptId":"u26"},
    "ee5ca5d35c174d579416ba618c545e63":{
      "scriptId":"u27"},
    "f6eb16c5c79e4a42a2cd1d88f2b03689":{
      "scriptId":"u28"},
    "00083fc2567f4552a3d79bab2d71425b":{
      "scriptId":"u29"},
    "b116684b72ea428a8550b909092abb4c":{
      "scriptId":"u30"},
    "89a6551a81b74c89812e378ee1ca1080":{
      "scriptId":"u31"},
    "baa9c892a94946618921446e988f1b25":{
      "scriptId":"u32"},
    "14b3b0a1b3b14abdb468d6cf3ae870f3":{
      "scriptId":"u33"},
    "01209edc10c7425b8419f3582af9ebdc":{
      "scriptId":"u34"},
    "2c6715b38dfb4f4b9e49cd2bc255d5f4":{
      "scriptId":"u35"},
    "0beaf2aefa7842bda06a1c488ef4b888":{
      "scriptId":"u36"},
    "35a2823c0eef41c58c8639bed75f8cd0":{
      "scriptId":"u37"},
    "82b94a8e474340208fe97c48413517e2":{
      "scriptId":"u38"},
    "084cb8fc7eea47438296cd3e557a6a2a":{
      "scriptId":"u39"},
    "d3668c67a4df45578446979a3e57a390":{
      "scriptId":"u40"},
    "fb4f07ea39b3473b8bafb41de496e1bb":{
      "scriptId":"u41"},
    "86be1c6fc8d0415b8b26c06e1aa2c4ad":{
      "scriptId":"u42"},
    "4b12669e8fb54878850ded7b0a677f47":{
      "scriptId":"u43"},
    "3d47dba651cb4e8a827d7d9de9c2ed39":{
      "scriptId":"u44"},
    "ba2c91fd75f24da68bc4e871125db871":{
      "scriptId":"u45"},
    "ea24e9ac1f524c88a19c3e202a1a9691":{
      "scriptId":"u46"},
    "d3d67662549249b3a320be333195ecaa":{
      "scriptId":"u47"},
    "596c21f4a7ce4e9db849599a513a59a9":{
      "scriptId":"u48"},
    "57b0c843ed8144e9836e242a4b68a7e9":{
      "scriptId":"u49"},
    "59e5dbdcc4024b13babf18d5a4fc8141":{
      "scriptId":"u50"},
    "5e3b3046b12d494db255a051c6bf12df":{
      "scriptId":"u51"},
    "122fb1240e224dd1be53f60526daf381":{
      "scriptId":"u52"},
    "703e949747cc4c72bff439faed35c6f6":{
      "scriptId":"u53"},
    "9e55183bd8694ebb958dee3f312d30b7":{
      "scriptId":"u54"}}});