$axure.loadCurrentPage({
  "url":"erfolgeubersichteintrage.html",
  "generationDate":new Date(1396968461108.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fce85bfe446641ce87f13777646e697e",
    "type":"Axure:Page",
    "name":"ErfolgeÜbersichtEinträge",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b824f574c9eb45ab823429d40f9e46b7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"deb80ad0d04b4a34b85fddd7ac9eefc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF71AEC3},
            "location":{
              "x":0,
              "y":65},
            "size":{
              "width":320,
              "height":483},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8469c7e368474b0bbee8d9ae39aa0de3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF71AEC3},
                "location":{
                  "x":0,
                  "y":65},
                "size":{
                  "width":320,
                  "height":483},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/erfolg/u12.png"}},
{
          "id":"0af3af79b9684110854a091c951d745c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":40,
              "y":390},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C4},
            "linePattern":"solid",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f14afd7e564d04ad606a263b125368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":40,
                  "y":390},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C4},
                "linePattern":"solid",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Erfolg in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"erfolg.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/startseite/u4.png"}},
{
          "id":"c5426715cf3444b991b6ade9a33c517c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF43445A,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F8F9},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":10,
              "y":75},
            "size":{
              "width":300,
              "height":82},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e01407d2a46541b6a7ea68023b984e21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF43445A,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F8F9},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":10,
                  "y":75},
                "size":{
                  "width":300,
                  "height":82},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/erfolgeubersichteintrage/u11.png"}},
{
          "id":"8ca294f63ac440e0acdefab5d18c1b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF43445A,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F8F9},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":10,
              "y":165},
            "size":{
              "width":300,
              "height":112},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11042dbc527042e3b0727f0d11a9c624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF43445A,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F8F9},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":10,
                  "y":165},
                "size":{
                  "width":300,
                  "height":112},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/erfolgeubersichteintrage/u13.png"}},
{
          "id":"0380530a7b844825816a5a66301739cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":176},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc71343b22e048c5bc0e81b7fa520baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":176},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"b30ad9b112d444bf911feadc10023963",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":191},
            "size":{
              "width":240,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF43445B}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/erfolgeubersichteintrage/u17_line.png"}},
{
          "id":"499633694b454de296d402572826d803",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF43445A,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F8F9},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":10,
              "y":285},
            "size":{
              "width":300,
              "height":97},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96708c6ad5a14dcfa43555d4520bdb85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF43445A,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F8F9},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":10,
                  "y":285},
                "size":{
                  "width":300,
                  "height":97},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/erfolgeubersichteintrage/u18.png"}},
{
          "id":"d3d449557e284d8e9b2a6ee7a79537ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":296},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee772d5e63b484b820bf8caf6fa0066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":296},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"888158d27bcc4b0a831d42cb20bede52",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":311},
            "size":{
              "width":240,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF43445B}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/erfolgeubersichteintrage/u17_line.png"}},
{
          "id":"9660611b0fe04b9482fad23407dbb20f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":40,
              "y":435},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C4},
            "linePattern":"solid",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f70c4f5be64d2399b7cb7722ece392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":40,
                  "y":435},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C4},
                "linePattern":"solid",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Auswahlseite in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"auswahlseite.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/startseite/u4.png"}}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}}},
  "objectPaths":{
    "b824f574c9eb45ab823429d40f9e46b7":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "deb80ad0d04b4a34b85fddd7ac9eefc4":{
      "scriptId":"u7"},
    "8469c7e368474b0bbee8d9ae39aa0de3":{
      "scriptId":"u8"},
    "0af3af79b9684110854a091c951d745c":{
      "scriptId":"u9"},
    "f7f14afd7e564d04ad606a263b125368":{
      "scriptId":"u10"},
    "c5426715cf3444b991b6ade9a33c517c":{
      "scriptId":"u11"},
    "e01407d2a46541b6a7ea68023b984e21":{
      "scriptId":"u12"},
    "8ca294f63ac440e0acdefab5d18c1b51":{
      "scriptId":"u13"},
    "11042dbc527042e3b0727f0d11a9c624":{
      "scriptId":"u14"},
    "0380530a7b844825816a5a66301739cb":{
      "scriptId":"u15"},
    "cc71343b22e048c5bc0e81b7fa520baa":{
      "scriptId":"u16"},
    "b30ad9b112d444bf911feadc10023963":{
      "scriptId":"u17"},
    "499633694b454de296d402572826d803":{
      "scriptId":"u18"},
    "96708c6ad5a14dcfa43555d4520bdb85":{
      "scriptId":"u19"},
    "d3d449557e284d8e9b2a6ee7a79537ff":{
      "scriptId":"u20"},
    "7ee772d5e63b484b820bf8caf6fa0066":{
      "scriptId":"u21"},
    "888158d27bcc4b0a831d42cb20bede52":{
      "scriptId":"u22"},
    "9660611b0fe04b9482fad23407dbb20f":{
      "scriptId":"u23"},
    "b6f70c4f5be64d2399b7cb7722ece392":{
      "scriptId":"u24"}}});