$axure.loadCurrentPage({
  "url":"fb_selbstkonzept5.html",
  "generationDate":new Date(1396968457863.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a636db3ad29f459ea5489c0f1c1354b4",
    "type":"Axure:Page",
    "name":"FB Selbstkonzept5",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42e964a2d95d4451a40bc64a2cf43594",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"69e657826d73485783a47e2b135d85f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d06999de35ac4fe7bbc123a8a5fc1510"},
{
          "id":"3664572764c848cabfcb338f2a9401ab",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":105},
            "size":{
              "width":310,
              "height":443}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"afbdb0fb60c54d8f8b1d71e082c2b1dd",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b4fa197aabd147eb98df01c3c4bf501c",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":295}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3de065e5c8894eb9b861430a0a9961c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":295}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/fb_selbstkonzept5/u17.png"}},
{
                  "id":"e5014d7cbd864b25b2ce83d5997e3dcd",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":90},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56fe4fbbbf4046d59688b5f25bf51da3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":90},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"d561caf9df654c1394854ccaf6d5f022",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":90},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ce3398a98724a85b7ce3e2fdd3a3ff7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":90},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4f8c5392baa54f7db9290bf7a5b280af",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":130},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"caf41788ea67481d89a9ddd6d737db1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":130},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ff56230061714486bac90a03c9cbbae1",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":170},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97123e462d514e83bc1b3ced503bf1a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":170},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5b16887a3f2b4e64b33f8339e744fe3d",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":130},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d36f3d1346054978ad147cb223944333",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":130},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"c50ffe5862d64d4abed72af94cbe4547",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":170},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f3e5145e0434447bca871ffbbdb30b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":170},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"842dbe7e7d204d80a290182350c2adae",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":210},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"520c9a4f75f04968b7cbecc76cb790d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":210},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"15135d5c78d144e2b7b3454964dbe0b1",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":250},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a4e843a8294470e9eac161116097cb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":250},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5fd63f96caed4eba9cb58c9277e120f3",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":210},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ea9be1849b4494baa65f094cc2f04c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":210},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"8d7c688bf70c45c09171b79024c9cdb0",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":250},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c26b80ef09a0426599ee7a224ecc2583",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":250},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"20879e8039d945dfb8fb352616eb35ca",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":305},
                    "size":{
                      "width":300,
                      "height":270}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b102cc955ced41709db8f729ca4e33fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":305},
                        "size":{
                          "width":300,
                          "height":270}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/nutzerdaten/u30.png"}},
{
                  "id":"128d2ec96d9646258ee2b453d7e5c470",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":395},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b362516d3fdd49458258e73e10d4f573",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":395},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"70dfd18081a34885916146d0593e7a75",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":395},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86e8d6373d9648d1aa24a4d0dd62d274",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":395},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6ba22cddc06249328e396bb540e557cd",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":435},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae5ea005342046959021b8e59351189b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":435},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b7e9f30675074b7c903e45b32140ddff",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":475},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"915b5f7178bf423999f73b243b85187f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":475},
                        "size":{
                          "width":230,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fa908e50e3244c7d8e052fe0106dc2be",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":435},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94178cb3b81241b58ff2124731bce9f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":435},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"b064463a812c42019e32dacd19367ae0",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":475},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4d45380decf47d2b6dba2d7e2434779",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":475},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"09e168c8b9e04fcfa28de850af0a272c",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":515},
                    "size":{
                      "width":230,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06762702068c4b038886b94b36ce45e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":60,
                          "y":515},
                        "size":{
                          "width":230,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c58c89a442c48b5b46b09e1b4c49298",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "stateStyles":{
                      "selected":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":515},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"3"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"084bc6b3ff5b4c709bd188277803aa4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "stateStyles":{
                          "selected":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF43445B}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":515},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"3"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set is selected of This equal to &quot;true&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetCheckState",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"true",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pc_kenntnisse/u31.png",
                    "selected~":"images/registrierung/u19.png"}},
{
                  "id":"da99d2a1f0264bb8a2a386a052730034",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEBE7B3},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":635},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d60442e1f803484b8179d6d86bfcb047",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEBE7B3},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":10,
                          "height":635},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/fb_selbstkonzept5/u57.png"}},
{
                  "id":"c5f7660b32e94d84b6b5285283c16181",
                  "label":"",
                  "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":585},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7de08fc7dadd4a9482201c96326c863e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3664572764c848cabfcb338f2a9401ab",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":585},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Beispiel in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"beispiel.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2a5ccd64dd6e4b89a56bc5d43c2c045c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1582067c5ddb4ebdbcd2f4f70ec927dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"c9a57cf80fab400daaee3c2cf2ebf929",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":45,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5df7598da51c449f9f884720410d9949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":45,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"01ad70cf31c24eb68e9bff7d493ce176",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":70,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aaa277bafba46fb9da2cd0fc778b58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":70,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"abc7890b616a4924acbf7bde0a0b27cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF424242,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":95,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f10031cd2f489fbda8d8cab1c38d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF424242,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":95,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u26.png"}},
{
          "id":"1ad0d0b240264a149cbf69a5cb5c4d45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFEFFFE,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":120,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"480e4e4128b24abf8853c3ce49f4a7e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFEFFFE,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":120,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/alter_geschlecht/u24.png"}}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}},
    "d06999de35ac4fe7bbc123a8a5fc1510":{
      "packageId":"d06999de35ac4fe7bbc123a8a5fc1510",
      "type":"Axure:Master",
      "name":"Master Selbstkonzept",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"75adf6f749014a10be2ea38894d0ff55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":55,
                "y":0},
              "size":{
                "width":265,
                "height":60},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68cbf0eece824d31b1220db2183b25a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":55,
                    "y":0},
                  "size":{
                    "width":265,
                    "height":60},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u8.png"}},
{
            "id":"470b815c9bb1491e93076b3163d6d959",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial'",
              "opacity":"1",
              "location":{
                "x":65,
                "y":21},
              "size":{
                "width":114,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c52e4711cc3491faad8084185273f60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial'",
                  "opacity":"1",
                  "location":{
                    "x":65,
                    "y":21},
                  "size":{
                    "width":114,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f4cc8beddcf34ae08a39d3198ed73974",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF5F8F9},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":30},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5e30c0764e4c41708e4425a0bd5b110a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF5F8F9},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alter_geschlecht/u12.png"}},
{
            "id":"0699841899a2417685f75b75c11cf0fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEBE7B3},
              "location":{
                "x":0,
                "y":95},
              "size":{
                "width":320,
                "height":453},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aa3b59a5f3d4dfe995ab4b83b709569",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEBE7B3},
                  "location":{
                    "x":0,
                    "y":95},
                  "size":{
                    "width":320,
                    "height":453},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/alter_geschlecht/u14.png"}}]}}},
  "objectPaths":{
    "42e964a2d95d4451a40bc64a2cf43594":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "69e657826d73485783a47e2b135d85f6":{
      "scriptId":"u7",
      "75adf6f749014a10be2ea38894d0ff55":{
        "scriptId":"u8"},
      "68cbf0eece824d31b1220db2183b25a5":{
        "scriptId":"u9"},
      "470b815c9bb1491e93076b3163d6d959":{
        "scriptId":"u10"},
      "8c52e4711cc3491faad8084185273f60":{
        "scriptId":"u11"},
      "f4cc8beddcf34ae08a39d3198ed73974":{
        "scriptId":"u12"},
      "5e30c0764e4c41708e4425a0bd5b110a":{
        "scriptId":"u13"},
      "0699841899a2417685f75b75c11cf0fe":{
        "scriptId":"u14"},
      "1aa3b59a5f3d4dfe995ab4b83b709569":{
        "scriptId":"u15"}},
    "3664572764c848cabfcb338f2a9401ab":{
      "scriptId":"u16"},
    "b4fa197aabd147eb98df01c3c4bf501c":{
      "scriptId":"u17"},
    "3de065e5c8894eb9b861430a0a9961c2":{
      "scriptId":"u18"},
    "e5014d7cbd864b25b2ce83d5997e3dcd":{
      "scriptId":"u19"},
    "56fe4fbbbf4046d59688b5f25bf51da3":{
      "scriptId":"u20"},
    "d561caf9df654c1394854ccaf6d5f022":{
      "scriptId":"u21"},
    "0ce3398a98724a85b7ce3e2fdd3a3ff7":{
      "scriptId":"u22"},
    "4f8c5392baa54f7db9290bf7a5b280af":{
      "scriptId":"u23"},
    "caf41788ea67481d89a9ddd6d737db1c":{
      "scriptId":"u24"},
    "ff56230061714486bac90a03c9cbbae1":{
      "scriptId":"u25"},
    "97123e462d514e83bc1b3ced503bf1a5":{
      "scriptId":"u26"},
    "5b16887a3f2b4e64b33f8339e744fe3d":{
      "scriptId":"u27"},
    "d36f3d1346054978ad147cb223944333":{
      "scriptId":"u28"},
    "c50ffe5862d64d4abed72af94cbe4547":{
      "scriptId":"u29"},
    "7f3e5145e0434447bca871ffbbdb30b6":{
      "scriptId":"u30"},
    "842dbe7e7d204d80a290182350c2adae":{
      "scriptId":"u31"},
    "520c9a4f75f04968b7cbecc76cb790d9":{
      "scriptId":"u32"},
    "15135d5c78d144e2b7b3454964dbe0b1":{
      "scriptId":"u33"},
    "3a4e843a8294470e9eac161116097cb6":{
      "scriptId":"u34"},
    "5fd63f96caed4eba9cb58c9277e120f3":{
      "scriptId":"u35"},
    "2ea9be1849b4494baa65f094cc2f04c6":{
      "scriptId":"u36"},
    "8d7c688bf70c45c09171b79024c9cdb0":{
      "scriptId":"u37"},
    "c26b80ef09a0426599ee7a224ecc2583":{
      "scriptId":"u38"},
    "20879e8039d945dfb8fb352616eb35ca":{
      "scriptId":"u39"},
    "b102cc955ced41709db8f729ca4e33fd":{
      "scriptId":"u40"},
    "128d2ec96d9646258ee2b453d7e5c470":{
      "scriptId":"u41"},
    "b362516d3fdd49458258e73e10d4f573":{
      "scriptId":"u42"},
    "70dfd18081a34885916146d0593e7a75":{
      "scriptId":"u43"},
    "86e8d6373d9648d1aa24a4d0dd62d274":{
      "scriptId":"u44"},
    "6ba22cddc06249328e396bb540e557cd":{
      "scriptId":"u45"},
    "ae5ea005342046959021b8e59351189b":{
      "scriptId":"u46"},
    "b7e9f30675074b7c903e45b32140ddff":{
      "scriptId":"u47"},
    "915b5f7178bf423999f73b243b85187f":{
      "scriptId":"u48"},
    "fa908e50e3244c7d8e052fe0106dc2be":{
      "scriptId":"u49"},
    "94178cb3b81241b58ff2124731bce9f0":{
      "scriptId":"u50"},
    "b064463a812c42019e32dacd19367ae0":{
      "scriptId":"u51"},
    "f4d45380decf47d2b6dba2d7e2434779":{
      "scriptId":"u52"},
    "09e168c8b9e04fcfa28de850af0a272c":{
      "scriptId":"u53"},
    "06762702068c4b038886b94b36ce45e8":{
      "scriptId":"u54"},
    "0c58c89a442c48b5b46b09e1b4c49298":{
      "scriptId":"u55"},
    "084bc6b3ff5b4c709bd188277803aa4b":{
      "scriptId":"u56"},
    "da99d2a1f0264bb8a2a386a052730034":{
      "scriptId":"u57"},
    "d60442e1f803484b8179d6d86bfcb047":{
      "scriptId":"u58"},
    "c5f7660b32e94d84b6b5285283c16181":{
      "scriptId":"u59"},
    "7de08fc7dadd4a9482201c96326c863e":{
      "scriptId":"u60"},
    "2a5ccd64dd6e4b89a56bc5d43c2c045c":{
      "scriptId":"u61"},
    "1582067c5ddb4ebdbcd2f4f70ec927dc":{
      "scriptId":"u62"},
    "c9a57cf80fab400daaee3c2cf2ebf929":{
      "scriptId":"u63"},
    "5df7598da51c449f9f884720410d9949":{
      "scriptId":"u64"},
    "01ad70cf31c24eb68e9bff7d493ce176":{
      "scriptId":"u65"},
    "1aaa277bafba46fb9da2cd0fc778b58c":{
      "scriptId":"u66"},
    "abc7890b616a4924acbf7bde0a0b27cd":{
      "scriptId":"u67"},
    "16f10031cd2f489fbda8d8cab1c38d1d":{
      "scriptId":"u68"},
    "1ad0d0b240264a149cbf69a5cb5c4d45":{
      "scriptId":"u69"},
    "480e4e4128b24abf8853c3ce49f4a7e6":{
      "scriptId":"u70"}}});