$axure.loadCurrentPage({
  "url":"startseite.html",
  "generationDate":new Date(1396968452281.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fadc9094bb9940ad80c136fde66b0633",
    "type":"Axure:Page",
    "name":"Startseite",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a6b1f9390ff425191c4e1b2f93e8534",
          "label":"Placeholder for App Content",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f8559c2762458fa5e5d2c6e620944f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/startseite/placeholder_for_app_content_u0.png"}},
{
          "id":"5cd19050ba5947a681a5e889347f4b07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":548}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfcc7a58076e4fafb5700da4dac52bcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":548}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/startseite/u2.jpg"}},
{
          "id":"7e62390adef54bafa16b354887740dd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":50,
              "y":355},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C4},
            "linePattern":"solid",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70cde9889824aa3ac0dd6bf4d957fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":50,
                  "y":355},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C4},
                "linePattern":"solid",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Login in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"login.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/startseite/u4.png"}},
{
          "id":"71a83c58afab4670a0a9012cee55c923",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF43445B},
            "location":{
              "x":50,
              "y":405},
            "size":{
              "width":220,
              "height":40},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC6C6C4},
            "linePattern":"solid",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b046d272b2484be79f6b2e78b481da74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF43445B},
                "location":{
                  "x":50,
                  "y":405},
                "size":{
                  "width":220,
                  "height":40},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC6C6C4},
                "linePattern":"solid",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Registrierung in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"registrierung.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/startseite/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4a6b1f9390ff425191c4e1b2f93e8534":{
      "scriptId":"u0"},
    "84f8559c2762458fa5e5d2c6e620944f":{
      "scriptId":"u1"},
    "5cd19050ba5947a681a5e889347f4b07":{
      "scriptId":"u2"},
    "bfcc7a58076e4fafb5700da4dac52bcc":{
      "scriptId":"u3"},
    "7e62390adef54bafa16b354887740dd2":{
      "scriptId":"u4"},
    "d70cde9889824aa3ac0dd6bf4d957fa2":{
      "scriptId":"u5"},
    "71a83c58afab4670a0a9012cee55c923":{
      "scriptId":"u6"},
    "b046d272b2484be79f6b2e78b481da74":{
      "scriptId":"u7"}}});