$axure.loadCurrentPage({
  "url":"kontakt.html",
  "generationDate":new Date(1396968458768.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4b11a153e061476bb82ea06ca4d3946f",
    "type":"Axure:Page",
    "name":"Kontakt",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"63a04018fe094832aba6d3a2b576f98a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"1e3cc1dd2c384722aa8178b0a779410c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"72ebae53829c4dcb9e50ebc955eeb799"},
{
          "id":"022ba374079743ad833069f23cb0789a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":75},
            "size":{
              "width":310,
              "height":473}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"beb73c73ee1b4c5eb671dcd1ce9c906f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0fcd5d0a79424d1ab799459fc9e59623",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":130},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef5e29f858374728839b164fdf09a03b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":130},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/beispiel/u17.png"}},
{
                  "id":"8187ff3c842a4d23b74adf20cf6dfcb2",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":430},
                    "size":{
                      "width":300,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38b74ad5fc3e4e2ea037ca68751ec830",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":430},
                        "size":{
                          "width":300,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/kontakt/u17.png"}},
{
                  "id":"e2a08d8c8bec4023890c6fd23429a1eb",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":510},
                    "size":{
                      "width":280,
                      "height":70}},
                  "adaptiveStyles":{
}},
{
                  "id":"4b0225a7bab743c3b8cf927b4647758c",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEBE7B3},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":710},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e2d8c000da240ddb049ff43dd9632cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEBE7B3},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":10,
                          "height":710},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/kontakt/u20.png"}},
{
                  "id":"3bb5d650990e4253afbfd5b44b367f1f",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":660},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3228366741224c6097d0582b720e0201",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":660},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Auswahlseite in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"auswahlseite.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}},
{
                  "id":"2cc0ac4c7c974567b05e02a1e734a5e3",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":300,
                      "height":130},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c8d42981172424fbdcbdbec5df03f6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":140},
                        "size":{
                          "width":300,
                          "height":130},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/beispiel/u17.png"}},
{
                  "id":"6c88db2a624a4f6e90333109732ec0bf",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":280},
                    "size":{
                      "width":300,
                      "height":140},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ed94c367d79489bb82608eb95638e51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":280},
                        "size":{
                          "width":300,
                          "height":140},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/fb_selbstkonzept1/u31.png"}},
{
                  "id":"22b5ef5737e64a1a908e9ae9d5f0c3a1",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":160,
                      "y":595},
                    "size":{
                      "width":100,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5be5f862a6e546709dc60efb609007cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":160,
                          "y":595},
                        "size":{
                          "width":100,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show danke_Nachricht01,<br>danke_Nachricht02",
                              "objectsToFades":[{
                                  "objectPath":["e56110d972734e38961a3fc97cccd6d2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["e5315a4a9f06412186461800a8bc52cf"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/kontakt/u28.png"}},
{
                  "id":"2383ae36175b406e8677f5b1e304f220",
                  "label":"",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":595},
                    "size":{
                      "width":100,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45f089d05d044464a858c0271d79fad6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":595},
                        "size":{
                          "width":100,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Auswahlseite in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"auswahlseite.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/kontakt/u28.png"}},
{
                  "id":"e56110d972734e38961a3fc97cccd6d2",
                  "label":"danke_Nachricht01",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":460},
                    "size":{
                      "width":220,
                      "height":100},
                    "visible":false,
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.34901961684227}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33655a74e8fe468c925d7749f776a270",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":460},
                        "size":{
                          "width":220,
                          "height":100},
                        "visible":false,
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5",
                        "outerShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.34901961684227}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/kontakt/danke_nachricht01_u32.png"}},
{
                  "id":"e5315a4a9f06412186461800a8bc52cf",
                  "label":"danke_Nachricht02",
                  "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":520},
                    "size":{
                      "width":220,
                      "height":40},
                    "visible":false,
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"235330d9ff3542e6b6a1894055dcb1d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"022ba374079743ad833069f23cb0789a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":520},
                        "size":{
                          "width":220,
                          "height":40},
                        "visible":false,
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Auswahlseite in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"auswahlseite.html",
                                "includeVariables":true},
                              "linkType":"current"},
{
                              "action":"fadeWidget",
                              "description":"Hide danke_Nachricht01,<br>danke_Nachricht02",
                              "objectsToFades":[{
                                  "objectPath":["e56110d972734e38961a3fc97cccd6d2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["e5315a4a9f06412186461800a8bc52cf"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}},
    "72ebae53829c4dcb9e50ebc955eeb799":{
      "packageId":"72ebae53829c4dcb9e50ebc955eeb799",
      "type":"Axure:Master",
      "name":"Master Kontakt",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"75adf6f749014a10be2ea38894d0ff55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":55,
                "y":0},
              "size":{
                "width":265,
                "height":60},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68cbf0eece824d31b1220db2183b25a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":55,
                    "y":0},
                  "size":{
                    "width":265,
                    "height":60},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u8.png"}},
{
            "id":"470b815c9bb1491e93076b3163d6d959",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial'",
              "opacity":"1",
              "location":{
                "x":65,
                "y":21},
              "size":{
                "width":72,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c52e4711cc3491faad8084185273f60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial'",
                  "opacity":"1",
                  "location":{
                    "x":65,
                    "y":21},
                  "size":{
                    "width":72,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0699841899a2417685f75b75c11cf0fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEBE7B3},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aa3b59a5f3d4dfe995ab4b83b709569",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEBE7B3},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u12.png"}}]}}},
  "objectPaths":{
    "63a04018fe094832aba6d3a2b576f98a":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "1e3cc1dd2c384722aa8178b0a779410c":{
      "scriptId":"u7",
      "75adf6f749014a10be2ea38894d0ff55":{
        "scriptId":"u8"},
      "68cbf0eece824d31b1220db2183b25a5":{
        "scriptId":"u9"},
      "470b815c9bb1491e93076b3163d6d959":{
        "scriptId":"u10"},
      "8c52e4711cc3491faad8084185273f60":{
        "scriptId":"u11"},
      "0699841899a2417685f75b75c11cf0fe":{
        "scriptId":"u12"},
      "1aa3b59a5f3d4dfe995ab4b83b709569":{
        "scriptId":"u13"}},
    "022ba374079743ad833069f23cb0789a":{
      "scriptId":"u14"},
    "0fcd5d0a79424d1ab799459fc9e59623":{
      "scriptId":"u15"},
    "ef5e29f858374728839b164fdf09a03b":{
      "scriptId":"u16"},
    "8187ff3c842a4d23b74adf20cf6dfcb2":{
      "scriptId":"u17"},
    "38b74ad5fc3e4e2ea037ca68751ec830":{
      "scriptId":"u18"},
    "e2a08d8c8bec4023890c6fd23429a1eb":{
      "scriptId":"u19"},
    "4b0225a7bab743c3b8cf927b4647758c":{
      "scriptId":"u20"},
    "5e2d8c000da240ddb049ff43dd9632cf":{
      "scriptId":"u21"},
    "3bb5d650990e4253afbfd5b44b367f1f":{
      "scriptId":"u22"},
    "3228366741224c6097d0582b720e0201":{
      "scriptId":"u23"},
    "2cc0ac4c7c974567b05e02a1e734a5e3":{
      "scriptId":"u24"},
    "8c8d42981172424fbdcbdbec5df03f6a":{
      "scriptId":"u25"},
    "6c88db2a624a4f6e90333109732ec0bf":{
      "scriptId":"u26"},
    "1ed94c367d79489bb82608eb95638e51":{
      "scriptId":"u27"},
    "22b5ef5737e64a1a908e9ae9d5f0c3a1":{
      "scriptId":"u28"},
    "5be5f862a6e546709dc60efb609007cc":{
      "scriptId":"u29"},
    "2383ae36175b406e8677f5b1e304f220":{
      "scriptId":"u30"},
    "45f089d05d044464a858c0271d79fad6":{
      "scriptId":"u31"},
    "e56110d972734e38961a3fc97cccd6d2":{
      "scriptId":"u32"},
    "33655a74e8fe468c925d7749f776a270":{
      "scriptId":"u33"},
    "e5315a4a9f06412186461800a8bc52cf":{
      "scriptId":"u34"},
    "235330d9ff3542e6b6a1894055dcb1d1":{
      "scriptId":"u35"}}});