$axure.loadCurrentPage({
  "url":"fb_selbstkonzept.html",
  "generationDate":new Date(1396968455257.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bcf5dc20bd61484181dacd86b1d7fb09",
    "type":"Axure:Page",
    "name":"FB Selbstkonzept",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42e964a2d95d4451a40bc64a2cf43594",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"13604e56590a457b8c7677279e1c8a88"},
{
          "id":"22409fcfcccd4ab79b85d9b0522f4a0d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a425e35edeab4a5cb61d4df721ad78a0"},
{
          "id":"1d09e796ff594e52a54d7e1af34c6ec8",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":75},
            "size":{
              "width":310,
              "height":473}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"48bec10539424ec9aa9db434a86afda4",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6e53b6bf43ef43378898502d2dd78d01",
                  "label":"",
                  "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":300,
                      "height":525},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3631a9b6880d415394c782543a970294",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":300,
                          "height":525},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/fb_selbstkonzept/u15.png"}},
{
                  "id":"0048336e34cf4ad19c5c2a2aa1c107e3",
                  "label":"",
                  "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFEBE7B3},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":630},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1df446850a684620a7f603e918755daa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFEBE7B3},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":10,
                          "height":630},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/fb_selbstkonzept/u17.png"}},
{
                  "id":"1d863835bc9d47689077b6c1554d07a6",
                  "label":"",
                  "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":535},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"83d9b76036f14df08cf3027b7c48fab1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":535},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open FB Selbstkonzept1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"fb_selbstkonzept1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}},
{
                  "id":"e5d91fcacb844327a02f6e1afd528ea9",
                  "label":"",
                  "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF43445B},
                    "location":{
                      "x":40,
                      "y":580},
                    "size":{
                      "width":220,
                      "height":40},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC6C6C4},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21355f21146d4cdb8e63127df315217d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d09e796ff594e52a54d7e1af34c6ec8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF43445B},
                        "location":{
                          "x":40,
                          "y":580},
                        "size":{
                          "width":220,
                          "height":40},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC6C6C4},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Beispiel in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"beispiel.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/startseite/u4.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "13604e56590a457b8c7677279e1c8a88":{
      "packageId":"13604e56590a457b8c7677279e1c8a88",
      "type":"Axure:Master",
      "name":"Master Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ec64a1f3691475aa5bc73c68e687b2a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":65}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a354018e678a4669a4ae0cbcc32fdb81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":65}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u1.jpg"}},
{
            "id":"952a16c0fc8244d3841b188cd55aaf6f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e46c7b9b93749c28ff87c2b47a558a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u3.png"}},
{
            "id":"273a1321e4aa454b8a88b454d57d7960",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":60,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"379d3312ba844d6aa3a67b44eea82830",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":60,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Startseite in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"startseite.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/registrierung/u5.jpg"}}]}},
    "a425e35edeab4a5cb61d4df721ad78a0":{
      "packageId":"a425e35edeab4a5cb61d4df721ad78a0",
      "type":"Axure:Master",
      "name":"Master Selbstkonzept start",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"75adf6f749014a10be2ea38894d0ff55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF43445B},
              "location":{
                "x":55,
                "y":0},
              "size":{
                "width":265,
                "height":60},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68cbf0eece824d31b1220db2183b25a5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF43445B},
                  "location":{
                    "x":55,
                    "y":0},
                  "size":{
                    "width":265,
                    "height":60},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u8.png"}},
{
            "id":"470b815c9bb1491e93076b3163d6d959",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial'",
              "opacity":"1",
              "location":{
                "x":65,
                "y":21},
              "size":{
                "width":114,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c52e4711cc3491faad8084185273f60",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial'",
                  "opacity":"1",
                  "location":{
                    "x":65,
                    "y":21},
                  "size":{
                    "width":114,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0699841899a2417685f75b75c11cf0fe",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFEBE7B3},
              "location":{
                "x":0,
                "y":65},
              "size":{
                "width":320,
                "height":483},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1aa3b59a5f3d4dfe995ab4b83b709569",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFEBE7B3},
                  "location":{
                    "x":0,
                    "y":65},
                  "size":{
                    "width":320,
                    "height":483},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/registrierung/u12.png"}}]}}},
  "objectPaths":{
    "42e964a2d95d4451a40bc64a2cf43594":{
      "scriptId":"u0",
      "0ec64a1f3691475aa5bc73c68e687b2a":{
        "scriptId":"u1"},
      "a354018e678a4669a4ae0cbcc32fdb81":{
        "scriptId":"u2"},
      "952a16c0fc8244d3841b188cd55aaf6f":{
        "scriptId":"u3"},
      "4e46c7b9b93749c28ff87c2b47a558a8":{
        "scriptId":"u4"},
      "273a1321e4aa454b8a88b454d57d7960":{
        "scriptId":"u5"},
      "379d3312ba844d6aa3a67b44eea82830":{
        "scriptId":"u6"}},
    "22409fcfcccd4ab79b85d9b0522f4a0d":{
      "scriptId":"u7",
      "75adf6f749014a10be2ea38894d0ff55":{
        "scriptId":"u8"},
      "68cbf0eece824d31b1220db2183b25a5":{
        "scriptId":"u9"},
      "470b815c9bb1491e93076b3163d6d959":{
        "scriptId":"u10"},
      "8c52e4711cc3491faad8084185273f60":{
        "scriptId":"u11"},
      "0699841899a2417685f75b75c11cf0fe":{
        "scriptId":"u12"},
      "1aa3b59a5f3d4dfe995ab4b83b709569":{
        "scriptId":"u13"}},
    "1d09e796ff594e52a54d7e1af34c6ec8":{
      "scriptId":"u14"},
    "6e53b6bf43ef43378898502d2dd78d01":{
      "scriptId":"u15"},
    "3631a9b6880d415394c782543a970294":{
      "scriptId":"u16"},
    "0048336e34cf4ad19c5c2a2aa1c107e3":{
      "scriptId":"u17"},
    "1df446850a684620a7f603e918755daa":{
      "scriptId":"u18"},
    "1d863835bc9d47689077b6c1554d07a6":{
      "scriptId":"u19"},
    "83d9b76036f14df08cf3027b7c48fab1":{
      "scriptId":"u20"},
    "e5d91fcacb844327a02f6e1afd528ea9":{
      "scriptId":"u21"},
    "21355f21146d4cdb8e63127df315217d":{
      "scriptId":"u22"}}});